/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class eu_project_rapid_demoapp_HelloJNI */

#ifndef _Included_eu_project_rapid_demoapp_HelloJNI
#define _Included_eu_project_rapid_demoapp_HelloJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     eu_project_rapid_demoapp_HelloJNI
 * Method:    print
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_eu_project_rapid_demoapp_HelloJNI_print
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
