/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class eu_project_rapid_demo_helloJNI_HelloJNI */

#ifndef _Included_eu_project_rapid_demo_helloJNI_HelloJNI
#define _Included_eu_project_rapid_demo_helloJNI_HelloJNI
#ifdef __cplusplus
extern "C" {
#endif
#undef eu_project_rapid_demo_helloJNI_HelloJNI_serialVersionUID
#define eu_project_rapid_demo_helloJNI_HelloJNI_serialVersionUID -5942880824910953975LL
/*
 * Class:     eu_project_rapid_demo_helloJNI_HelloJNI
 * Method:    print
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_eu_project_rapid_demo_helloJNI_HelloJNI_print
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
